### ISSUE TITLE
Show placeholder text instead of 0s.

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitballs#49]
Currently, the `players` page __Weight__ and __Height__ inputs default to showing `0` instead of their placeholder values as is shown below.

![localhost_5000_dev_html__players](https://cloud.githubusercontent.com/assets/78602/13164955/9c23013a-d67e-11e5-95b8-d066d1beec90.png)

This almost certainly has to do with a `type` converter changing the empty string `input.value` into `0`.  

We might need a good solution for this, even adding a feature to CanJS.

**Comment by justinbmeyer** [comment]
https://github.com/canjs/canjs/blob/master/map/define/doc/examples/make-model-year.html#L110

**Comment by justinbmeyer** [comment]
`{($value})`="convertToString(~weight)"

**Comment by jandjorgensen** [comment]
Starting on this.

Problem:
An empty string (or falsey value) is converted to 0's (and produces a "0" in the field instead of the desired empty string) when using `{($value)}` and the define plugin with `{type: 'number'}`.

Possible approaches:
1. Custom type as linked to in the comment above
2.  A conversion helper as shown above
3. Updating the built-in `number` type to handle this automatically
4.  Updating the `{($value)}` helper to handle this automatically

Between 3 & 4, I think 4 is more appropriate since it's a display issue. For now, to close this issue for bitballs I'll stick with 1.

**Comment by justinbmeyer** [comment]
This is no longer working it seems.  And it can be made to work the right way with the recent changes to CanJS.

Please make a `util` helper.  It should look like what's outlined in: https://github.com/canjs/canjs/issues/2299
